### ISSUE TITLE
pipenv install using >10.1.2 fails with TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by stephendonner** [pypa/pipenv#1595]
Using pipenv >= 11.0.0,

```pipenv install --system -r requirements.txt --skip-lock --deploy``` fails to install dependencies, with:

```
<snip>
TypeError: 'NoneType' object has no attribute '__getitem__'
The command '/bin/sh -c pipenv install --system -r requirements.txt --skip-lock --deploy' returned a non-zero code: 1
```
##### Describe your environment

1. Mac OS + Alpine:2.7 (Docker)
1. Python version: `$ python -V`, ****2.7.14-r0****
1. Pipenv version: `$ pipenv --version`, ****pipenv, version 11.1.3****

##### Expected result

```Step 6/8 : RUN pipenv install --system -r requirements.txt --skip-lock --deploy
 ---> Running in 345e73504077
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Installing dependencies from Pipfile…
<snip of Docker stuff>
Successfully built da3c8f5d8907
```

##### Actual result

```
Stephens-MBP:e2e stephendonner$ docker build -t bouncer-tests .
Sending build context to Docker daemon   72.7kB
Step 1/8 : FROM python:2.7-alpine
 ---> 0781c116c406
Step 2/8 : RUN apk add --update gcc libffi-dev musl-dev openssl-dev python-dev
 ---> Using cache
 ---> 3bfab50971e8
Step 3/8 : WORKDIR /src
 ---> Using cache
 ---> 0b5ca6f723d9
Step 4/8 : COPY requirements.txt /src
 ---> Using cache
 ---> 1a82af11a273
Step 5/8 : RUN pip install pipenv==11.1.3
 ---> Using cache
 ---> f758686208fd
Step 6/8 : RUN pipenv install --verbose --system -r requirements.txt --skip-lock --deploy
 ---> Running in 5e482c74160e
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 197, in install
    selective_upgrade=selective_upgrade
  File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 1731, in do_install
    ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy, skip_requirements=skip_requirements)
  File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 652, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 342, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/project.py", line 439, in create_pipfile
    data[u'requires'] = {'python_version': python_version(self.which('python'))[:len('2.7')]}
TypeError: 'NoneType' object has no attribute '__getitem__'
/usr/local/lib/python2.7/site-packages/pipenv/utils.py:1147: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-WJUzoA-requirements'>
  warnings.warn(warn_message, ResourceWarning)
The command '/bin/sh -c pipenv install --verbose --system -r requirements.txt --skip-lock --deploy' returned a non-zero code: 1
```

##### Steps to replicate

1. Clone https://github.com/mozilla-services/go-bouncer/tree/master/tests/e2e
2. ```docker build -t bouncer-tests .```

This works with ```pipenv==10.1.2```:

```
Stephens-MBP:e2e stephendonner$ docker build -t bouncer-tests .
Sending build context to Docker daemon   72.7kB
Step 1/8 : FROM python:2.7-alpine
2.7-alpine: Pulling from library/python
81033e7c1d6a: Pull complete 
9b61101706a6: Pull complete 
32753c857922: Pull complete 
27040272194a: Pull complete 
Digest: sha256:c0989b6c77d408476029a3f1776947f88674acfab9d2b9a6bf4b4a6235bcac3d
Status: Downloaded newer image for python:2.7-alpine
 ---> 0781c116c406
Step 2/8 : RUN apk add --update gcc libffi-dev musl-dev openssl-dev python-dev
 ---> Running in ad11a210bff4
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/20) Installing binutils-libs (2.26-r1)
(2/20) Installing binutils (2.26-r1)
(3/20) Installing gmp (6.1.0-r0)
(4/20) Installing isl (0.14.1-r0)
(5/20) Installing libgomp (5.3.0-r0)
(6/20) Installing libatomic (5.3.0-r0)
(7/20) Installing libgcc (5.3.0-r0)
(8/20) Installing pkgconf (0.9.12-r0)
(9/20) Installing pkgconfig (0.25-r1)
(10/20) Installing mpfr3 (3.1.2-r0)
(11/20) Installing mpc1 (1.0.3-r0)
(12/20) Installing libstdc++ (5.3.0-r0)
(13/20) Installing gcc (5.3.0-r0)
(14/20) Installing libffi (3.2.1-r2)
(15/20) Installing libffi-dev (3.2.1-r2)
(16/20) Installing musl-dev (1.1.14-r16)
(17/20) Installing zlib-dev (1.2.11-r0)
(18/20) Installing openssl-dev (1.0.2n-r0)
(19/20) Installing python (2.7.14-r0)
(20/20) Installing python-dev (2.7.14-r0)
Executing busybox-1.24.2-r14.trigger
OK: 165 MiB in 52 packages
Removing intermediate container ad11a210bff4
 ---> fd747ec88258
Step 3/8 : WORKDIR /src
Removing intermediate container e6a310293486
 ---> d4a13360659e
Step 4/8 : COPY requirements.txt /src
 ---> dde78dc4978e
Step 5/8 : RUN pip install pipenv==10.1.2
 ---> Running in e88aad7c4624
Collecting pipenv==10.1.2
  Downloading pipenv-10.1.2.tar.gz (3.9MB)
Collecting virtualenv (from pipenv==10.1.2)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
Collecting pew>=0.1.26 (from pipenv==10.1.2)
  Downloading pew-1.1.2-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in /usr/local/lib/python2.7/site-packages (from pipenv==10.1.2)
Collecting requests>2.18.0 (from pipenv==10.1.2)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting urllib3>=1.21.1 (from pipenv==10.1.2)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting pathlib; python_version == "2.7" (from pew>=0.1.26->pipenv==10.1.2)
  Downloading pathlib-1.0.1.tar.gz (49kB)
Collecting shutilwhich; python_version == "2.7" (from pew>=0.1.26->pipenv==10.1.2)
  Downloading shutilwhich-1.1.0.tar.gz
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from pew>=0.1.26->pipenv==10.1.2)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=17.1 in /usr/local/lib/python2.7/site-packages (from pew>=0.1.26->pipenv==10.1.2)
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv==10.1.2)
  Downloading virtualenv_clone-0.3.0-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>2.18.0->pipenv==10.1.2)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests>2.18.0->pipenv==10.1.2)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests>2.18.0->pipenv==10.1.2)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
Building wheels for collected packages: pipenv, pathlib, shutilwhich
  Running setup.py bdist_wheel for pipenv: started
  Running setup.py bdist_wheel for pipenv: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e6/d7/a3/1ca2bd6facf67e58a0823a971825972accb1aff7014803a6a8
  Running setup.py bdist_wheel for pathlib: started
  Running setup.py bdist_wheel for pathlib: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2a/23/a5/d8803db5d631e9f391fe6defe982a238bf5483062eeb34e841
  Running setup.py bdist_wheel for shutilwhich: started
  Running setup.py bdist_wheel for shutilwhich: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/0e/28/70/d5cc6586f26d614b26901485f6f6072d35cbbb5bbeffb6ea43
Successfully built pipenv pathlib shutilwhich
Installing collected packages: virtualenv, pathlib, shutilwhich, backports.shutil-get-terminal-size, virtualenv-clone, pew, urllib3, idna, chardet, certifi, requests, pipenv
Successfully installed backports.shutil-get-terminal-size-1.0.0 certifi-2018.1.18 chardet-3.0.4 idna-2.6 pathlib-1.0.1 pew-1.1.2 pipenv-10.1.2 requests-2.18.4 shutilwhich-1.1.0 urllib3-1.22 virtualenv-15.1.0 virtualenv-clone-0.3.0
Removing intermediate container e88aad7c4624
 ---> b28422e1903e
Step 6/8 : RUN pipenv install --system -r requirements.txt --skip-lock --deploy
 ---> Running in 345e73504077
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Installing dependencies from Pipfile…
Removing intermediate container 345e73504077
 ---> f38c847f6fb9
Step 7/8 : COPY . /src
 ---> 62e756c7909d
Step 8/8 : CMD pytest
 ---> Running in f50ce3831328
Removing intermediate container f50ce3831328
 ---> da3c8f5d8907
Successfully built da3c8f5d8907
Successfully tagged bouncer-tests:latest
```

/cc @davehunt

**Comment by kennethreitz** [comment]
thanks for the report

**Comment by kennethreitz** [comment]
you are not using this as intended.

**Comment by kennethreitz** [comment]
--deploy is for deploying lockfiles.

**Comment by stephendonner** [comment]
Thanks for taking the time to look at this; actually, for my use-case, it appears the culprit here is ```--system```; removing ```--deploy``` on its own still fails:

https://gist.github.com/stephendonner/efc541e416c0f9c0e95598651f01de62

Removing ```--system```, yet leaving in ```--deploy``` yields me a passing build:

https://gist.github.com/stephendonner/54b88ba57b4aef2779a5d42a6db1bbbf
