### ISSUE TITLE
pipenv's tests fail on Python 3.11 release candidate

### ISSUE THREAD

**Issue by cclauss** [pypa/pipenv#5252]
See the Python 3.11 [test results](https://github.com/pypa/pipenv/pull/5245/checks) on pull request #5245 where **Ubuntu** and **Windows** fail 2 tests and **macOS** fails 4 tests.
* https://www.python.org/download/pre-releases

Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by oz123** [comment]
The Mac OS X test fail recently on all versions.
As to Python3.11:
The real issue is here:

```

  File "/home/runner/work/pipenv/pipenv/pipenv/vendor/pipdeptree.py", line 111, in __init__
    self.project_name = obj.project_name
                        ^^^^^^^^^^^^^^^^
AttributeError: 'PathDistribution' object has no attribute 'project_name'
```
This might be solved by updating the pideptree version we use.

**Comment by oz123** [comment]
There is already a WIP to fix it:

https://github.com/naiquevin/pipdeptree/pull/169

**Comment by dqkqd** [comment]
This should be fixed with new version of `pipdeptree`. https://github.com/tox-dev/pipdeptree/pull/173

**Comment by oz123** [comment]
Thanks, I'll submit a PR to bump the vendored version later this week.

**Comment by oz123** [comment]
See #5343

**Comment by Wiznik1002** [comment]
Pipenv not working on python 3.11.4 ubuntu

**Comment by matteius** [comment]
@Wiznik1002 That is not helpful -- please open a new issue report.
