### ISSUE TITLE
Latest pipenv version(2025.0.4) is not compatible with python 3.14

### ISSUE THREAD

**Issue by Ivan-Lukianov** [pypa/pipenv#6439]
### Issue description

Seems like pipenv is not compatible with latest python 3.14.

### Expected result

No error when running pipenv install

### Actual result

We are getting this error:

```
#12 8.599   File "/usr/local/lib/python3.14/site-packages/pipenv/project.py", line 1174, in generate_package_pipfile_entry
#12 8.599     req_name = determine_package_name(package)
#12 8.599   File "/usr/local/lib/python3.14/site-packages/pipenv/utils/dependencies.py", line 840, in determine_package_name
#12 8.599     req_name = find_package_name_from_directory(package.link.file_path)
#12 8.599   File "/usr/local/lib/python3.14/site-packages/pipenv/utils/dependencies.py", line 697, in find_package_name_from_directory
#12 8.599     possible_name = find_package_name_from_filename(path.name, file)
#12 8.599   File "/usr/local/lib/python3.14/site-packages/pipenv/utils/dependencies.py", line 865, in find_package_name_from_filename
#12 8.599     possible_name = parse_setup_file(content)
#12 8.599   File "/usr/local/lib/python3.14/site-packages/pipenv/utils/dependencies.py", line 588, in parse_setup_file
#12 8.599     elif isinstance(keyword.value, ast.Str):
#12 8.599                                    ^^^^^^^
#12 8.599 AttributeError: module 'ast' has no attribute 'Str'
#12 ERROR: process "/bin/sh -c pipenv install ." did not complete successfully: exit code: 1
```

### Steps to replicate

Run pipenv install command with pipenv version `2025.0.4`.

### Notes

I think this line doesn't work in python 3.14 - https://github.com/pypa/pipenv/blob/main/pipenv/utils/dependencies.py#L565

**Comment by Gyllsdorff** [comment]
https://docs.python.org/3/library/ast.html#module-ast
> **Deprecated since version 3.8:** Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases.

https://docs.python.org/3.14/whatsnew/3.14.html#id9
> **ast**
> Remove the following classes, which have been deprecated aliases of [Constant](https://docs.python.org/3.14/library/ast.html#ast.Constant) since Python 3.8 and have emitted deprecation warnings since Python 3.12:
[...]
Str

The change that removed `ast.String`: https://github.com/python/cpython/pull/119563/files

**Comment by matteius** [comment]
https://github.com/pypa/pipenv/releases/tag/v2025.1.1
