### ISSUE TITLE
Support for python 3.6.0 broken due to pip bug in newly vendored version

### ISSUE THREAD

**Issue by mungojam** [pypa/pipenv#5008]
### Issue description

We are hitting https://github.com/pypa/pip/issues/10280 in the latest version of pipenv because it updated to a version that suffers from the bug (21.2.2). We need to use the latest version of pipenv in order to allow us to update to later versions of python using pyenv-win, so we're in a bit of a catch-22.

The bug was fixed in 21.2.4, so please could you release a patched version that uses this.

I see that you are planning on dropping 3.6 support in a later version (https://github.com/pypa/pipenv/pull/4966), so I hope you can get this fix in before making that change.

### Expected result

pipenv to work with 3.6.0 so that we can easily update our tools to later versions of python using recent pyenv-win fixes.

### Actual result

pipenv is not usable due to the pip error happening when running `pipenv install` and I can't provide our team with a simple way to gradually update python across our tools using pyenv-win.

The error is:

>   File "c:\users\me\appdata\roaming\python\python36\site-packages\pipenv\patched\notpip\_internal\models\link.py", line 288, in links_equivalent
    return _CleanResult.from_link(link1) == _CleanResult.from_link(link2)
AttributeError: type object '_CleanResult' has no attribute 'from_link'

### Steps to replicate

Hopefully not needed, I'm just hitting the bug listed in the pip issue above.

Sorry, it's got too much internal info in it, but hopefully you have enough to go on

**Comment by matteius** [comment]
@mungojam Just noting that it was `2021.11.5` and `2021.11.5.post0` that changed from `pip==20.0.2` to `pip==21.2.2`.  I am going to see if there is much work to update the vendoring of to `pip==21.2.4`, but do note Python 3.6 is EOL so expect that there will be very few remaining releases to support py3.6.

**Comment by matteius** [comment]
@mungojam That branch is passing its build if you want to try it and report back if it solved the issue for you.  https://github.com/pypa/pipenv/pull/5009

**Comment by mungojam** [comment]
> @mungojam That branch is passing its build if you want to try it and report back if it solved the issue for you.  https://github.com/pypa/pipenv/pull/5009

Thanks for putting together so quickly, I'll take a look today or this evening

**Comment by mungojam** [comment]
> @mungojam That branch is passing its build if you want to try it and report back if it solved the issue for you. #5009

@matteius that's sorted it yes
