### ISSUE TITLE
pipenv check 'package safety' still not working on pipenv-2018.5.18

### ISSUE THREAD

**Issue by GuillaumeLegoy** [pypa/pipenv#2354]
Hello,

##### Expected result

Similar issue to [#1996](https://github.com/pypa/pipenv/issues/1996l), but still not working even though it's marked as resolved.

##### Actual result

>Checking PEP 508 requirements…
>Passed!
>Checking installed package safety…
>An error occurred:
>Traceback (most recent call last):
>  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
>    "__main__", mod_spec)
>  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>   exec(code, run_globals)
>  File "/home/guillaumel/.local/lib/python2.7/site-packages/pipenv/patched/safety.zip/__main__.py", >line 8, in <module>
>  File "/home/guillaumel/.local/lib/python2.7/site-packages/pipenv/patched/safety.zip/click/core.py", line >722, in __call__
>  File "/home/guillaumel/.local/lib/python2.7/site-packages/pipenv/patched/safety.zip/click/core.py", line >697, in main
>  File "/home/guillaumel/.local/lib/python2.7/site-packages/pipenv/patched/safety.zip/click/core.py", line >1066, in invoke
>  File "/home/guillaumel/.local/lib/python2.7/site-packages/pipenv/patched/safety.zip/click/core.py", line >895, in invoke
>  File "/home/guillaumel/.local/lib/python2.7/site-packages/pipenv/patched/safety.zip/click/core.py", line >535, in invoke
>  File "/home/guillaumel/.local/lib/python2.7/site-packages/pipenv/patched/safety.zip/safety/cli.py", line >52, in check
>AttributeError: module 'pip' has no attribute 'get_installed_distributions'`

##### Steps to replicate

`pipenv check`
